# Generated by blankcut's release pipeline for v0.19.0. Do not edit by hand:
# the next release overwrites this file.
class Blankcut < Formula
  desc "Command-line interface for the Blank Cut platform"
  homepage "https://blankcut.com"
  version "0.19.0"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.0/blankcut_Darwin_arm64.tar.gz"
      sha256 "850ceab1f2e74ba0e2b1640e178057c90ae11635eae8fc57aac6b41d9d34aa78"
    else
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.0/blankcut_Darwin_amd64.tar.gz"
      sha256 "0b2942fde5c9c669e0d219b0439dff46df3f7bb646a57995a11910b715e438b4"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.0/blankcut_Linux_arm64.tar.gz"
      sha256 "49b5bde5c13d95ece795c9de90ac813bee55e765a0c1755089d7ca4a5e8c0ef0"
    else
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.0/blankcut_Linux_amd64.tar.gz"
      sha256 "6bcf390d475e5080791aaaeabadd8cf2ef9c5d53ec2ba657583af4440ddc2487"
    end
  end

  def install
    bin.install "blankcut"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blankcut --version")
  end
end
