# Generated by blankcut's release pipeline for v0.19.1. Do not edit by hand:
# the next release overwrites this file.
class Blankcut < Formula
  desc "Command-line interface for the Blank Cut platform"
  homepage "https://blankcut.com"
  version "0.19.1"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.1/blankcut_Darwin_arm64.tar.gz"
      sha256 "a25279aafe19be1779bfe2e83bbcd92cc65a2e0b6edf6d7cbdcbee6adaee785f"
    else
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.1/blankcut_Darwin_amd64.tar.gz"
      sha256 "def6c79ef481500fbdef030e94298de9051cf5fd88499dcfa20f236164a543d5"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.1/blankcut_Linux_arm64.tar.gz"
      sha256 "f279d46298222afa043755c2fbbf46417767123a490da8c256ffb08207d1eccf"
    else
      url "https://github.com/Blankcut/blankcut-cli-releases/releases/download/v0.19.1/blankcut_Linux_amd64.tar.gz"
      sha256 "d23e669654c50127a7e441b395c766e4952d7dc02220d89a1390f2c13b68f126"
    end
  end

  def install
    bin.install "blankcut"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blankcut --version")
  end
end
